{% set name = "mkl-service" %}
{% set version = "2.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/IntelPython/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 61cc4bfadb390c9d1adb8293df1b5d901f34a9cce947253775d8de9175ed1453

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  ignore_run_exports:
    - blas
    - mkl-service
  skip: true  # [osx or (not x86_64) or py<310 or py>315]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake
    - ninja-base
  host:
    - python
    - pip
    - meson-python >=0.13.0
    - meson >=1.8.3
    - cython >=3.1.0
    - mkl-devel {{ mkl }}
  run:
    - python
    - mkl

test:
  imports:
    - mkl
  commands:
    - pip check
    - pytest -vv --pyargs mkl
  requires:
    - pip
    - pytest

about:
  home: https://github.com/IntelPython/mkl-service
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  description: |
    Intel(R) Math Kernel Library (Intel(R) MKL) support functions are
    subdivided into the following groups according to their purpose, such as
    Version Information, Threading Control, Timing, Memory Management,
    Conditional Numerical Reproducibility Control, and Miscellaneous.
  summary: Python hooks for Intel(R) Math Kernel Library runtime control settings.
  dev_url: https://github.com/IntelPython/mkl-service
  doc_url: https://github.com/IntelPython/mkl-service

extra:
  skip-lints:
    - cbc_dep_in_run_missing_from_host
  recipe-maintainers:
     - oleksandr-pavlyk
