{% set name = "mkl-service" %}
{% set version = "2.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/IntelPython/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6dfd59d47dc68d5f89555ccf137dcc9a1154be3e2cef282fcdbc96399f0dc70c
  patches:
    - patches/0001-enable-python-3.15.patch

build:
  number: 0
  ignore_run_exports:
    - blas
    - mkl-service
  skip: true  # [osx or (linux and aarch64) or py<315 or py>=316]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - wheel >=0.45.1
    - setuptools >=77
    - cython
    - mkl-devel {{ mkl }}
  run:
    - python
    - mkl

test:
  imports:
    - mkl
  commands:
    - pytest -vv --pyargs mkl
  requires:
    - pytest

about:
  home: https://github.com/IntelPython/mkl-service
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  description:
      Intel(R) Math Kernel Library (Intel(R) MKL) support functions are
      subdivided into the following groups according to their purpose, such as
          Version Information
          Threading Control
          Timing
          Memory Management
          Conditional Numerical Reproducibility Control
          Miscellaneous
  summary: Python hooks for Intel(R) Math Kernel Library runtime control settings.
  dev_url: https://github.com/IntelPython/mkl-service
  doc_url: https://github.com/IntelPython/mkl-service

extra:
  skip-lints:
    - cbc_dep_in_run_missing_from_host
  recipe-maintainers:
     - oleksandr-pavlyk
