{% set version = "2.5.2" %}

package:
  name: mkl-service
  version: {{ version }}

source:
  url: https://github.com/IntelPython/mkl-service/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ee5506eb95ff1f4d67cd5f3e5b4648d752900dd10af8219f9b3857b306945a56

build:
  skip: True  # [not x86 or osx]
  number: 0
  ignore_run_exports:
    - blas
    - mkl-service

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - mkl-devel {{ mkl }}
    - cython
  run:
    - python
    - mkl

test:
  requires:
    - pytest
  imports:
    - mkl
  commands:
    - pytest -vv --pyargs mkl
  source_files:
    - mkl/tests

about:
  home: https://github.com/IntelPython/mkl-service
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  description:
      Intel(R) Math Kernel Library (Intel(R) MKL) support functions are
      subdivided into the following groups according to their purpose, such as
          Version Information
          Threading Control
          Timing
          Memory Management
          Conditional Numerical Reproducibility Control
          Miscellaneous
  summary: Python hooks for Intel(R) Math Kernel Library runtime control settings.
  dev_url: https://github.com/IntelPython/mkl-service
  doc_url: https://github.com/IntelPython/mkl-service

extra:
  skip-lints:
    - cbc_dep_in_run_missing_from_host
  recipe-maintainers:
     - oleksandr-pavlyk
